language: node_js
node_js:
  - 12

os:
  - linux
dist: focal

script:
  - echo "Skipping tests"

deploy:
  provider: lambda
  function_name: "html-to-pdf"
  region: "us-east-2"
  role: "arn:aws:iam::843380199157:user/travis"
  runtime: "nodejs12.x"
  handler_name: "handler"
  on:
    branch: main
